In [50]:
import numpy as np

In [82]:
N = 128
x = np.random.randn(128,128)

class arr():
    def __init__(self, x):
        self.y = np.zeros(x.shape)
        self.z = np.zeros(x.shape)

In [83]:
intx, inty = np.meshgrid(np.arange(N), np.arange(N))

def permut(x, intx, inty):
    arr1 = arr(x)
    for i in range(N):
        for j in range(N):
            arr1.y[i,j] = x[intx[i,j], inty[i,j]]
            arr1.z[i,j] = x[intx[i,j], inty[i,j]]
                        
%timeit for i in range(10):permut(x,intx,inty)

1 loops, best of 3: 269 ms per loop


In [87]:
@jit
def sum2d(x, intx, inty, N):
    y = np.zeros(x.shape)
    z = np.zeros(x.shape)
    for i in range(N):
        for j in range(N):
            y[i,j] = x[intx[i,j], inty[i,j]]
            z[i,j] = x[intx[i,j], inty[i,j]]
            
    return y,z
            
%timeit for i in range(10):sum2d(x,intx,inty, N)

The slowest run took 243.37 times longer than the fastest. This could mean that an intermediate result is being cached 
1 loops, best of 3: 1.04 ms per loop


In [43]:
it = np.nditer(a, flags=['multi_index'], op_flags=['writeonly'])

while not it.finished:
    print "%d, %s" %(it[0], it.multi_index)
    it[0] = b[it.multi_index[0], it.multi_index[1]]
    it.iternext()
print a
print b

0, (0, 0)
1, (0, 1)
2, (0, 2)
3, (1, 0)
4, (1, 1)
5, (1, 2)
[[-0.82734478  0.16644506 -1.03011769]
 [ 0.05852371  1.21518809 -1.78707343]]
[[-0.82734478  0.16644506 -1.03011769]
 [ 0.05852371  1.21518809 -1.78707343]]


In [60]:
from numba import jit